spring:
  application:
    name: sistema-cadastro-empresa-cliente
  
  datasource:
    url:  jdbc:postgresql://localhost:5432/SolarDetect
    username: postgres
    password: 123a123a
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true